mkdir -p shortcuts
ln -sf generic XXX_NOP
ln -sf ../generic shortcuts/XXXNOP
ln -sf generic XXX_SET_HISTORY_RATE
ln -sf ../generic shortcuts/XXXHIRA
ln -sf generic XXX_SET_PARAM
ln -sf ../generic shortcuts/XXXSETPA
ln -sf generic XXX_CLEAR_VARS
ln -sf ../generic shortcuts/XXXCLRV
ln -sf generic XXX_SEND_EXTENDTELEM
ln -sf ../generic shortcuts/XXXEXTM
ln -sf generic XXX_WHICH_NEEDS_LONG_TIME
ln -sf ../generic shortcuts/XXXLONG
ln -sf generic TST_NOP
ln -sf ../generic shortcuts/TSTNOP
ln -sf generic GLB_NOP
ln -sf ../generic shortcuts/GLBNOP
ln -sf generic GLB_SEND_EXTENDED_TM
ln -sf ../generic shortcuts/GLBEXTM
ln -sf generic CMM_NOP
ln -sf ../generic shortcuts/CMMNOP
ln -sf generic CMM_SET_VERBOSITY
ln -sf ../generic shortcuts/CMMVERV
ln -sf generic CMM_SET_IN_LEOP
ln -sf ../generic shortcuts/CMMINLE
ln -sf generic CMM_SET_OUT_OF_LEOP
ln -sf ../generic shortcuts/CMMOUTLE
ln -sf generic CMM_GOTOSAFEMODE
ln -sf ../generic shortcuts/CMMSAFE
ln -sf generic CMM_SET_MODE
ln -sf ../generic shortcuts/CMMMODE
ln -sf generic CMD_NOP
ln -sf ../generic shortcuts/CMDNOPE
ln -sf generic HKE_NOP
ln -sf ../generic shortcuts/HKENOP
ln -sf generic HKE_SET_RATE
ln -sf ../generic shortcuts/HKESETRA
ln -sf generic HKE_START_DOWNLINK
ln -sf ../generic shortcuts/HKEDOWON
ln -sf generic HKE_STOP_DOWNLINK
ln -sf ../generic shortcuts/HKEDOWOF
ln -sf generic TCM_NOP
ln -sf ../generic shortcuts/TCMNOP
ln -sf generic TCM_CLEAR_TT_LIST
ln -sf ../generic shortcuts/TCMCLRLS
ln -sf generic TCM_ACTIVATE_PENDING_CMDS
ln -sf ../generic shortcuts/TCMACTVC
ln -sf generic TCM_DELETE_PENDING_CMDS
ln -sf ../generic shortcuts/TCMDELC
ln -sf generic TCM_SEND_TT_LIST
ln -sf ../generic shortcuts/TCMSNDLS
ln -sf generic TMC_APPEND_TIME_TIMED_CMD
ln -sf ../generic shortcuts/TMCAPPCM
ln -sf generic ANM_NOP
ln -sf ../generic shortcuts/ANMNOP
ln -sf generic ANM_SEND_REPORT
ln -sf ../generic shortcuts/ANMREPR
ln -sf generic ANM_SEND_RINGBUFFER
ln -sf ../generic shortcuts/ANMSENRG
ln -sf generic ANM_CLEAR_ERR_COUNTER
ln -sf ../generic shortcuts/ANMCLRER
ln -sf generic BOM_NOP
ln -sf ../generic shortcuts/BOMNOP
ln -sf generic BOM_JUMP_TO_BOOTIMAGE
ln -sf ../generic shortcuts/BOMJMP
ln -sf generic BOM_REINIT_BOOT_LIST
ln -sf ../generic shortcuts/BOMREIN
ln -sf generic BOM_APPEND_BOOT_IDYX
ln -sf ../generic shortcuts/BOMAPP
ln -sf generic BOM_SEND_BOOTLIST
ln -sf ../generic shortcuts/BOMSEND
ln -sf generic BOM_REBOOT
ln -sf ../generic shortcuts/BOMREBO
ln -sf generic BOM_CHECK_BOOTIMAGE
ln -sf ../generic shortcuts/BOMCHECK
ln -sf generic POD_NOP
ln -sf ../generic shortcuts/PODNOP
ln -sf generic POD_ENABLE_CONTROL
ln -sf ../generic shortcuts/PODON
ln -sf generic POD_DISABLE_CONTROL
ln -sf ../generic shortcuts/PODUNTOF
ln -sf generic POD_UNIT_ON
ln -sf ../generic shortcuts/PODUNTON
ln -sf generic POD_UNIT_OFF
ln -sf ../generic shortcuts/PODOFF
ln -sf generic POD_SETCONF_BITMAP
ln -sf ../generic shortcuts/PODBMAP
ln -sf generic POD_SET_RANGE
ln -sf ../generic shortcuts/PODRANG
ln -sf generic POD_SEND_PWR_SETTINGS
ln -sf ../generic shortcuts/PODSEND
ln -sf generic TER_NOP
ln -sf ../generic shortcuts/TERNOP
ln -sf generic TER_ENABLE_CONTROL
ln -sf ../generic shortcuts/TERON
ln -sf generic TER_DISABLE_CONTROL
ln -sf ../generic shortcuts/TEROFF
ln -sf generic TER_HEATER_ON
ln -sf ../generic shortcuts/TERHEA1
ln -sf generic TER_HEATER_OFF
ln -sf ../generic shortcuts/TERHEA0
ln -sf generic TER_HEATPIPE_CNTRL
ln -sf ../generic shortcuts/TERHEAP
ln -sf generic TER_SET_RANGE
ln -sf ../generic shortcuts/TERRANG
ln -sf generic RED_NOP
ln -sf ../generic shortcuts/REDNOP
ln -sf generic RED_SEND_DUL_TO_OTHERNODE
ln -sf ../generic shortcuts/REDSDULS
ln -sf generic RED_ACCEPT_DUL_OTHERNODE
ln -sf ../generic shortcuts/REDSDULA
ln -sf generic RED_RESET_PINPOG_CNT
ln -sf ../generic shortcuts/REDRSTP
ln -sf generic RED_TOGGLE_WORKER_MONITOR
ln -sf ../generic shortcuts/REDTOG
ln -sf generic RED_ENALBE_RECOVER_OTHER
ln -sf ../generic shortcuts/RECREC1
ln -sf generic RED_DISABLE_RECOVER_OTHER
ln -sf ../generic shortcuts/REDREC0
ln -sf generic WAT_NOP
ln -sf ../generic shortcuts/WATNOP
ln -sf generic WAT_RESET_NODE
ln -sf ../generic shortcuts/WATRSTND
ln -sf generic WAT_NOT_ALLOW_RESET
ln -sf ../generic shortcuts/WATDISBL
ln -sf generic WAT_ALLOW_RESET
ln -sf ../generic shortcuts/WATENABL
ln -sf generic TIM_NOP
ln -sf ../generic shortcuts/TIMNOPE
ln -sf generic TIM_SET_UTC
ln -sf ../generic shortcuts/TIMSETUT
ln -sf generic TIM_SET_LEAP
ln -sf ../generic shortcuts/TIMLEAP
ln -sf generic TIM_SET_UTC_DELTA
ln -sf ../generic shortcuts/TIMDELT
ln -sf generic TIM_ENABLE_DISTR_UTC
ln -sf ../generic shortcuts/MENDIS
ln -sf generic TIM_DISABLE_DISTR_UTC
ln -sf ../generic shortcuts/TIMDISDI
ln -sf generic TIM_ENABLE_1PPS_SYNC
ln -sf ../generic shortcuts/TIM1PPS1
ln -sf generic TIM_DISABLE_1PPS_SYNC
ln -sf ../generic shortcuts/TIM1PPS0
ln -sf generic TIM_SET_CLOCK_DRIFT
ln -sf ../generic shortcuts/TIMDRIF
ln -sf generic TIM_SEND_TIMEMODEL
ln -sf ../generic shortcuts/TIMSENDM
ln -sf generic DWL_NOP
ln -sf ../generic shortcuts/DWLNOP
ln -sf generic DWL_SET_LOW_RATE
ln -sf ../generic shortcuts/DWLLOW
ln -sf generic DWL_SET_HI_RATE
ln -sf ../generic shortcuts/DWLHI
ln -sf generic DWL_START_SBAND
ln -sf ../generic shortcuts/DWLSB1
ln -sf generic DWL_STOP_SBAND
ln -sf ../generic shortcuts/DWLSB0
ln -sf generic DWL_START_XBAND
ln -sf ../generic shortcuts/DWLXB1
ln -sf generic DWL_STOP_XBAND
ln -sf ../generic shortcuts/DWLXB0
ln -sf generic DWL_CONFIG_SBAND
ln -sf ../generic shortcuts/DWLSBCON
ln -sf generic DWL_CONFIG_XBAND
ln -sf ../generic shortcuts/DWLXBCON
ln -sf generic DWL_CONFIG_SBAND_RED
ln -sf ../generic shortcuts/DWLSRED
ln -sf generic DWL_CONFIG_XBAND_RED
ln -sf ../generic shortcuts/DWLXRED
ln -sf generic SFL_NOP
ln -sf ../generic shortcuts/SFLNOP
ln -sf generic SFL_GOTOSAFEMODE
ln -sf ../generic shortcuts/SFLSAFEM
ln -sf generic SFL_SET_MODE
ln -sf ../generic shortcuts/SFLSETMO
ln -sf generic SFL_SEND_SFLIST
ln -sf ../generic shortcuts/SFLSNDLS
ln -sf generic SFL_UPLOADLST
ln -sf ../generic shortcuts/SFLUPLLS
ln -sf generic SFL_NEXT_START_IN_LEOP
ln -sf ../generic shortcuts/SFLINLEO
ln -sf generic SFL_OUT_OF_LEOP
ln -sf ../generic shortcuts/SFLOUTLE
ln -sf generic SFL_REQUEST_STARTLIST
ln -sf ../generic shortcuts/SFLREQLS
ln -sf generic DUL_NOP
ln -sf ../generic shortcuts/DULNOP
ln -sf generic DUL_RESET_DUL_PROTOCOL
ln -sf ../generic shortcuts/DULRSTPR
ln -sf generic DUL_DISTRIBUTE_DATA
ln -sf ../generic shortcuts/DULDISTR
ln -sf generic DUL_WRITE_SEGMENT
ln -sf ../generic shortcuts/DULWRITE
ln -sf generic DUL_UPLOADBLOCK
ln -sf ../generic shortcuts/DULUPBLK
ln -sf generic DUL_CHECK_UPLOAD_SEG
ln -sf ../generic shortcuts/DULCKSEG
ln -sf generic SUR_NOP
ln -sf ../generic shortcuts/SURNOP
ln -sf generic SUR_SET_RANGES
ln -sf ../generic shortcuts/SURRANG
ln -sf generic SUR_ENABLE_THREAD_CHECK
ln -sf ../generic shortcuts/SURTHR1
ln -sf generic SUR_DISABLE_THREAD_CHECK
ln -sf ../generic shortcuts/SURTHR0
ln -sf generic SUR_ENABLE_MEM_CHECK
ln -sf ../generic shortcuts/SURMEM1
ln -sf generic SUR_DISABLE_MEM_CHECK
ln -sf ../generic shortcuts/SURMEM0
ln -sf generic SUR_SEND_ANALOGVALS
ln -sf ../generic shortcuts/SURSENDA
ln -sf generic SUR_ENABLE_LATCHUPPROT
ln -sf ../generic shortcuts/SURLATC1
ln -sf generic SUR_DISABLE_LATCHUPPROT
ln -sf ../generic shortcuts/SURLATC0
ln -sf generic ROV_NOP
ln -sf ../generic shortcuts/ROVNOP
ln -sf generic ROV_SEND_EXTENDED_TM
ln -sf ../generic shortcuts/ROVEXTM
ln -sf generic ROV_START_ANT_SCAN
ln -sf ../generic shortcuts/ROVSCNB
ln -sf generic ROV_STOP_ANT_SCAN
ln -sf ../generic shortcuts/ROVSCNS
ln -sf generic ROV_SET_ANT_POS
ln -sf ../generic shortcuts/ROVSTAPO
ln -sf generic ROV_STOP
ln -sf ../generic shortcuts/ROVSTOP
ln -sf generic ROV_CNTR_WHEEL
ln -sf ../generic shortcuts/ROVWHEE
ln -sf generic ROV_DRIVE
ln -sf ../generic shortcuts/ROVDRIVE
ln -sf generic ATC_NOP
ln -sf ../generic shortcuts/ATCNOP
ln -sf generic ATC_SET_ATC_MODE
ln -sf ../generic shortcuts/ATCMOD
ln -sf generic ATC_GOTO_ATC_SAFEMODE
ln -sf ../generic shortcuts/ATCSAFE
ln -sf generic ATC_GOTO_ATC_SUSPENMODE
ln -sf ../generic shortcuts/ATCSUSP
ln -sf generic GUI_NOP
ln -sf ../generic shortcuts/GUINOP
ln -sf generic NAV_NOP
ln -sf ../generic shortcuts/NAVNOP
ln -sf generic LND_NOP
ln -sf ../generic shortcuts/LNDNOP
ln -sf generic PAY_NOP
ln -sf ../generic shortcuts/PAYNOP
